spin_manifest_version = 2

[application]
name = "shopping-list"
version = "0.1.0"
authors = ["Jason Washburn <jason.washburn@gmail.com>"]
description = "A shopping list app build with go, spin, and htmx"

[[trigger.http]]
route = "/..."
component = "app"

[component.app]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "assets/", destination = "/" }]

[[trigger.http]]
route = "/api/..."
component = "api"

[component.api]
source = "api/main.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]
[component.api.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "api"
watch = ["**/*.go", "go.mod"]
